[theme]
base="light"
# gov navy
primaryColor="#0B3D91"
backgroundColor="#FFFFFF"
# soft card gray
secondaryBackgroundColor="#F3F6FA"
textColor="#0F172A"
font="sans serif"
showWidgetBorder=true
borderColor="#D7DEE9"

dataframeHeaderBackgroundColor="#EAF0FA"
dataframeBorderColor="#D7DEE9"

[theme.sidebar]
backgroundColor="#F3F6FA"
secondaryBackgroundColor="#FFFFFF"
textColor="#0F172A"
